# Generated by Django 3.1.5 on 2021-01-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReallyLongLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("original_link", models.URLField(max_length=1000)),
                ("long_link", models.CharField(max_length=2000)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
